name: DuelStuff
version: '${project.version}'
main: me.oud.main
commands:
  armorkit:
    description: Gives You Armored Kit.
    usage: /<command>
    aliases: akit
  noarmorkit:
    description: Gives You Non-Armored Kit.
    usage: /<command>
    aliases: nakit
  start:
    description: Starts The Match.
    usage: /<command>
    aliases: match