name: DuelStuff
version: '${project.version}'
main: me.oud.main
commands:
  armorkit:
    description: Gives You Armored Kit.
    usage: /<command>
    aliases: akit
  nonarmorkit:
    description: Gives You Non-Armored Kit.
    usage: /<command>
    aliases: nakit